### ISSUE TITLE
init script didn't work on CentOS/RedHat

### ISSUE THREAD

**Issue by barrowkwan** [sliim-cookbooks/glances#1]
log_daemon_msg, log_end_msg and start-stop-daemon doesn't exist on CentOS even with red-lsb installed.

**Comment by Sliim** [comment]
Hi!

Thanks for your feedback! I will look for this issue, do you have any suggestion?

**Comment by Sliim** [comment]
Hi!

I pushed a fix here: https://github.com/sliim-cookbooks/glances/pull/2
Tested with Centos 5, 6 and 7 (kitchen-docker)

Can you try this init script and tell me if it's ok for you?

Thanks.
